services:
  database:
    container_name: postgres-dev
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: projects-api-user
      POSTGRES_PASSWORD: projects-api-password
      POSTGRES_DB: projects-api-db
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

volumes:
  postgres-dev-data:
