services:
  database:
    container_name: personal-api-postgres-dev
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: personal-api-user
      POSTGRES_PASSWORD: personal-api-password
      POSTGRES_DB: personal-api-db
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

volumes:
  postgres-dev-data:
