projects-api:
  stage: Production
  production: true
  azure:
    storage:
      connection-string: \${AZURE_STORAGE_CONNECTION_STRING:}
  portfolio:
    api:
      url: https://albertv.dev/api
      secret: \${PORTFOLIO_API_SECRET:}

spring:
  datasource:
    url: \${SPRING_DATASOURCE_URL:}
    username: \${SPRING_DATASOURCE_USERNAME:}
    password: \${SPRING_DATASOURCE_PASSWORD:}

server:
  forward-headers-strategy: native

logging:
  level:
    dev:
      albertv:
        projects: INFO
    web: INFO
