projects-api:
  stage: Production
  production: true
  azure:
    storage:
      blob:
        endpoint: \${AZURE_BLOB_STORAGE_ENDPOINT:}
  portfolio:
    api:
      url: https://albertv.dev/api
      secret: \${PORTFOLIO_API_SECRET:}

spring:
  datasource:
    url: \${SPRING_DATASOURCE_URL:}
    username: \${SPRING_DATASOURCE_USERNAME:}
    password: \${SPRING_DATASOURCE_PASSWORD:}
