projects-api:
  stage: Production
  production: true
  portfolio:
    api:
      url: https://albertv.dev/api

server:
  forward-headers-strategy: native

logging:
  level:
    dev:
      albertv:
        projects: INFO
    web: INFO
