projects-api:
  stage: Development
  portfolio:
    api:
      url: http://localhost:3000/api
      secret: revalidate-secret

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projects-api-db
    username: projects-api-user
    password: projects-api-password
  jpa:
    show-sql: true
