projects-api:
  production: false
  cors:
    allowed-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
    allowed-headers: Access-Control-Allow-Headers, Access-Control-Allow-Origin, Authorization, X-Requested-With, X-Auth-Token, Content-Type, Accept, X-CSRF-TOKEN, X-Frame-Options
    exposed-headers: Content-Disposition
    allow-credentials: true
    max-age: 3600
  jwt:
    token:
      access:
        expiration: 900 # 15 minutes
      refresh:
        expiration: 604800 # 7 days
  azure:
    storage:
      blob:
        projects:
          container-name: projects
        skills:
          container-name: skills

spring:
  application:
    name: personal-api
    version: ${version}
  config:
    import: optional:secrets.yml
  jackson:
    default-property-inclusion: NON_NULL
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 3MB
  web:
    locale: en_US
    locale-resolver: fixed
  threads:
    virtual:
      enabled: true

springdoc:
  show-actuator: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true

management:
  endpoints:
    web:
      cors:
        allowed-origin-patterns: \${projects-api.cors.allowed-origins}
        allowed-methods: \${projects-api.cors.allowed-methods}
        allowed-headers: \${projects-api.cors.allowed-headers}
        exposed-headers: \${projects-api.cors.exposed-headers}
        allow-credentials: \${projects-api.cors.allow-credentials}
        max-age: \${projects-api.cors.max-age}
      exposure:
        include: info,health
  endpoint:
    info:
      access: read_only
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
    app:
      version: \${spring.application.version}
      stage: \${stage}
