# Personal-API
personal-api.production=false
## 15 minutes
personal-api.jwt.token.access.expiration=900
## 7 days
personal-api.jwt.token.refresh.expiration=604800
personal-api.azure.storage.blob.projects.container-name=projects
personal-api.azure.storage.blob.skills.container-name=skills

# Spring
spring.application.name=${name}
spring.config.import=optional:secrets.properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=3MB
spring.web.locale=en_US
spring.web.locale-resolver=fixed
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50
spring.threads.virtual.enabled=true

# Spring actuator
management.endpoints.web.exposure.include=info
management.info.env.enabled=true
management.endpoint.info.access=read_only

# App
info.app.name=Personal-API
info.app.version=${version}
