projects-api:
  production: true
  cors:
    allowed-origins: https://api.albertv.dev,https://albertv.dev,https://www.albertv.dev
  portfolio:
    api:
      url: https://albertv.dev/api

server:
  forward-headers-strategy: native

info:
  app:
    stage: Production

logging:
  level:
    dev:
      albertv:
        projects: INFO
    web: INFO
