ALTER TABLE API_USER ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE API_IMAGE ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE API_PROJECT ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE API_SKILL ALTER COLUMN ID DROP IDENTITY;

CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE IMAGE_SEQ;
CREATE SEQUENCE PROJECT_SEQ;
CREATE SEQUENCE SKILL_SEQ;

SELECT setval('USER_SEQ', coalesce((SELECT max(ID) FROM API_USER), 0));
SELECT setval('IMAGE_SEQ', coalesce((SELECT max(ID) FROM API_IMAGE), 0));
SELECT setval('PROJECT_SEQ', coalesce((SELECT max(ID) FROM API_PROJECT), 0));
SELECT setval('SKILL_SEQ', coalesce((SELECT max(ID) FROM API_SKILL), 0));
