ALTER TABLE API_USER ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE API_IMAGE ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE API_PROJECT ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE API_SKILL ALTER COLUMN ID DROP IDENTITY;

CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE IMAGE_SEQ;
CREATE SEQUENCE PROJECT_SEQ;
CREATE SEQUENCE SKILL_SEQ;

SELECT setval('USER_SEQ', (SELECT max(ID) FROM API_USER));
SELECT setval('IMAGE_SEQ', (SELECT max(ID) FROM API_IMAGE));
SELECT setval('PROJECT_SEQ', (SELECT max(ID) FROM API_PROJECT));
SELECT setval('SKILL_SEQ', (SELECT max(ID) FROM API_SKILL));
