DROP TABLE API_USER;

ALTER TABLE API_IMAGE RENAME TO IMAGE;
ALTER TABLE API_PROJECT RENAME TO PROJECT;
ALTER TABLE API_PROJECT_SKILL_MAP RENAME TO PROJECT_SKILL_MAP;
ALTER TABLE API_SKILL RENAME TO SKILL;
